name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "evening-crag-62279" #Must be unique in Heroku
          heroku_email: "jscho17@student.sdu.dk"
      - name: Testing
        run: mvn test -DskipTests=false -Dgroups=slow
      - name: Merge
        run: |
            git checkout ${GITHUB_REF#refs/heads/}
            git rebase origin/release
            git branch release
            git push origin release:release
            git push origin :${GITHUB_REF#refs/heads/}
